### ISSUE TITLE
how to use genai with proxy?

### ISSUE THREAD

**Issue by sorthman** [googleapis/python-genai#285]
Did genaiClient supply the proxy feature?

like :
client = genai.Client(
    api_key=GOOGLE_API_KEY,
    http_client=DefaultHttpxClient(
        proxy="http://XXXX.XXXXX:port",
        transport=httpx.HTTPTransport(local_address="0.0.0.0"),
    )
    http_options={'api_version': 'v1alpha'},
)

**Comment by chrisheecho** [comment]
It does not right now as you describe it but let me raise the priority on this and put it in the backlog

**Comment by yinghsienwu** [comment]
We use `AuthorizedSession` from google auth for sync requests, and `httpx.AsyncClient` for async requests. Both sync and async use `urllib.request.getproxies` from environment variables. 


Could you try something like this? 
```
import os

# User code
os.environ['HTTPS_PROXY'] = 'http://username:password@proxy_uri:port'
```

Then proceed with client initialization.

**Comment by liefra** [comment]
I am currently still experiencing issues with using a localhost proxy, as the `httpx ` package—unlike the `requests` package—does not automatically utilise the environment variables `SSL_CERT_FILE`, `REQUESTS_CA_BUNDLE` or `SSL_CERT_DIR`. This is confirmed in the [documentation](https://www.python-httpx.org/advanced/ssl/). As a result, I have not yet found a way to get localhost proxies to work.

I tried without success
```python
    os.environ['REQUESTS_CA_BUNDLE'] = 'client.pem'
    os.environ['SSL_CERT_FILE'] = 'client.pem'
    os.environ['HTTPS_PROXY'] = 'http://127.0.0.1:9111'
```

Is there a way to configure the httpx client?

```python
ctx = ssl.create_default_context(cafile="client.pem")
client = httpx.Client(verify=ctx)
```

**Comment by natarajan0007** [comment]
@liefra i was resolved this i put the resolution steps here . 
https://github.com/google/adk-python/issues/1

**Comment by yinghsienwu** [comment]
Thanks! We'll try to merge https://github.com/googleapis/python-genai/pull/573 asap.

**Comment by liefra** [comment]
Hi @natarajan0007 and @yinghsienwu : Thank you very much for your update and for merging the pull requests so promptly. Much appreciated.

**Comment by AmirHmZz** [comment]
@yinghsienwu We are still unable to use `socks5` proxy with env variables because httpx [does not accept](https://github.com/encode/httpx/blob/9e8ab40369bd3ec2cc8bff37ab79bf5769c8b00f/httpx/_utils.py#L40) `socks5` as proxy schema. In the other hand, httpx [supports](https://www.python-httpx.org/advanced/proxies/#socks) `socks5` proxy if we pass it via args to `httpx.Client()`.
Wouldn't it better to let developers pass kwargs directly to `httpx.Client`?
https://github.com/googleapis/python-genai/blob/b9d3be1e87a3e4260c16a3c36e0c728b330f831a/google/genai/_api_client.py#L448

**Comment by yinghsienwu** [comment]
@AmirHmZz You can pass it through `http_options = HttpOptions(client_arts=..., async_client_args=...)`, and then `client=Client(..., http_options=http_options)`.
